### ISSUE TITLE
Agregar responsiveness al texto

### ISSUE THREAD

**Issue by edjroz** [NgThundercats/NgThundercats.github.io#10]
![screenshot from 2017-03-02 10-43-49](https://cloud.githubusercontent.com/assets/14135788/23511955/5b0897d8-ff35-11e6-8e55-9ffb459b583a.png)

Display de 2 monitores 1280x1240. utilizando chrome y firefox (respectivamente)

**Comment by DiogenesPolanco** [comment]
#11
